devel_space: /home/fatoks/catkin_ws_user/odroid-devel
install: true
install_space: /home/fatoks/catkin_ws_user/odroid-install
profile: odroid
source_space: /home/fatoks/catkin_ws_user/src
workspace: /home/fatoks/catkin_ws_user
